config/routes.rb
Rails.application.routes.draw do
  
  resources :re_tweets do
    collection do
      get 'search'
    end
    member do
      post 'send_retweet'
    end
  end

  resources :guides

  resources :critters do 
    resources :identifying_images
    collection do
      get 'search'
    end
  end
  resources :birds,       controller: 'critters', type: 'Bird'
  resources :bugs,        controller: 'critters', type: 'Bug'
  resources :herps,        controller: 'critters', type: 'Herp'
  resources :insects,     controller: 'critters', type: 'Insect'
  resources :mammals,     controller: 'critters', type: 'Mammal'

  resources :plants
  
  resources :guides
  resources :sections
  resources :guide_items

  devise_for :explorers

  root 'index#index'

end

app/views/partials/_main_nav.html.erb
<!-- Entire Navbar Code -->
<ul class="nav-bar">
  <li class="<%= ap(root_path) %>"><%= link_to 'Home', root_path %></li>
  <li class="<%= ap(critters_path) %> has-flyout">
    <%= link_to 'Critters', critters_path %>
    <a href="#" class="flyout-toggle"><span> </span></a>
    <ul class="flyout">
      <li class="<%= ap(birds_path) %>"><%= link_to 'Birds', birds_path %><%= link_to 'New Bird', new_bird_path %></li>
      <li class="<%= ap(bugs_path) %>"><%= link_to 'Bugs', bugs_path %><%= link_to 'New Bug', new_bug_path %></li>
      <li class="<%= ap(herps_path) %>"><%= link_to 'Reptiles and Amphibians', herps_path %></li>
      <li class="<%= ap(insects_path) %>"><%= link_to 'Insects', insects_path %></li>
      <li class="<%= ap(mammals_path) %>"><%= link_to 'Mammals', mammals_path %></li>
    </ul>
  </li>
  <li class="<%= ap(guides_path) %>">
    <%= link_to 'Guides', guides_path %>
  </li>
</ul>