config/routes.rb
Rails.application.routes.draw do
  
  resources :re_tweets do
    collection do
      get 'search'
    end
    member do
      post 'send_retweet'
    end
  end

  resources :guides

  resources :critters do 
    resources :identifying_images
    collection do
      get 'search'
    end
  end
  resources :birds,       controller: 'critters', type: 'Bird'
  resources :bugs,        controller: 'critters', type: 'Bug'
  resources :herps,        controller: 'critters', type: 'Herp'
  resources :insects,     controller: 'critters', type: 'Insect'
  resources :mammals,     controller: 'critters', type: 'Mammal'

  resources :plants
  
  resources :guides
  resources :sections
  resources :guide_items

  devise_for :explorers

  root 'index#index'

end

app/models/guide_item.rb
class GuideItem < ActiveRecord::Base
  belongs_to :critter
  belongs_to :section
  
  def as_json(options = {})
    super(:only => [:id, :guide_id ], :include => {
        :critter => { :only => [:id, :name], :include => {
         :identifying_images => { :only => [ :image, :attribution ] }
       }}
    })
  end
  
end

app/controllers/guide_items_controller.rb
class GuideItemsController < ApplicationController
  before_action :set_guide_item, only: [:show, :edit, :update, :destroy]

  # GET /guide_items
  # GET /guide_items.json
  def index
    @guide_items = GuideItem.all
  end

  # GET /guide_items/1
  # GET /guide_items/1.json
  def show
    render json: @guide_item
  end

  # GET /guide_items/new
  def new
    @guide_item = GuideItem.new
  end

  # GET /guide_items/1/edit
  def edit
  end

  # POST /guide_items
  # POST /guide_items.json
  def create
    @guide_item = GuideItem.new(guide_item_params)

    respond_to do |format|
      if @guide_item.save
        format.html { redirect_to @guide_item, notice: 'Guide item was successfully created.' }
        format.json { render json: @guide_item, :only => :id, :include => {:critter => { :only => [ :id, :name ]}}}
      else
        format.html { render :new }
        format.json { render json: @guide_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guide_items/1
  # PATCH/PUT /guide_items/1.json
  def update
    respond_to do |format|
      if @guide_item.update(guide_item_params)
        format.html { redirect_to @guide_item, notice: 'Guide item was successfully updated.' }
        format.json { render :show, status: :ok, location: @guide_item }
      else
        format.html { render :edit }
        format.json { render json: @guide_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guide_items/1
  # DELETE /guide_items/1.json
  def destroy
    @guide_item.destroy
    respond_to do |format|
      format.html { redirect_to guide_items_url, notice: 'Guide item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guide_item
      @guide_item = GuideItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guide_item_params
      params.require(:guide_item).permit(:section_id, :critter_id)
    end
end

app/helpers/guide_items_helper.rb
module GuideItemsHelper
end

app/views/guide_items/_form.html.erb
<%= form_for(@guide_item) do |f| %>
  <% if @guide_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guide_item.errors.count, "error") %> prohibited this guide_item from being saved:</h2>

      <ul>
      <% @guide_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :section_id %><br>
    <%= f.number_field :section_id %>
  </div>
  <div class="field">
    <%= f.label :critter_id %><br>
    <%= f.number_field :critter_id %>
  </div>
  <div class="field">
    <%= f.label :section_index %><br>
    <%= f.number_field :section_index %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guide_items/edit.html.erb
<h1>Editing guide_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @guide_item %> |
<%= link_to 'Back', guide_items_path %>

app/views/guide_items/index.html.erb
<h1>Listing guide_items</h1>

<table>
  <thead>
    <tr>
      <th>Section</th>
      <th>Critter</th>
      <th>Section index</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guide_items.each do |guide_item| %>
      <tr>
        <td><%= guide_item.section_id %></td>
        <td><%= guide_item.critter_id %></td>
        <td><%= guide_item.section_index %></td>
        <td><%= link_to 'Show', guide_item %></td>
        <td><%= link_to 'Edit', edit_guide_item_path(guide_item) %></td>
        <td><%= link_to 'Destroy', guide_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guide item', new_guide_item_path %>

app/views/guide_items/new.html.erb
<h1>New guide_item</h1>

<%= render 'form' %>

<%= link_to 'Back', guide_items_path %>

app/views/guide_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Section:</strong>
  <%= @guide_item.section_id %>
</p>

<p>
  <strong>Critter:</strong>
  <%= @guide_item.critter_id %>
</p>

<p>
  <strong>Section index:</strong>
  <%= @guide_item.section_index %>
</p>

<%= link_to 'Edit', edit_guide_item_path(@guide_item) %> |
<%= link_to 'Back', guide_items_path %>